make public and rename tty style defs

diff --git a/src/lib/bashcli/init b/src/lib/bashcli/init
--- a/src/lib/bashcli/init
+++ b/src/lib/bashcli/init
@@ -1,17 +1,33 @@
 #!/usr/bin/env bash
 
-declare -g -A _BASHCLI_LIBRARIES_LOADED=()
-declare -g -A _BASHCLI_COLORS=(
-  error  $'\033[91m'
-  warn   $'\033[93m'
-  debug  $'\033[96m'
-  info   $'\033[92m'
-  none   $'\033[39m'
+:
+# shellcheck disable=SC2034
+declare -g -A BASHCLI_TTY_STYLES=(
+  error   $'\033[91m'
+  warn    $'\033[93m'
+  debug   $'\033[96m'
+  info    $'\033[92m'
+  success $'\033[92m'
+  failure $'\033[91m'
+  bold    $'\033[1m'
+  none    $'\033[39m'
 )
 
-if ! [ -t 2 ]; then
-  _BASHCLI_COLORS=()
+if [ -t 1 ]; then
+  declare -n BASHCLI_TTY_STDOUT_STYLES=BASHCLI_TTY_STYLES
+else
+  # shellcheck disable=SC2034
+  declare -g -A BASHCLI_TTY_STDOUT_STYLES=()
 fi
+
+if [ -t 2 ]; then
+  declare -n BASHCLI_TTY_STDERR_STYLES=BASHCLI_TTY_STYLES
+else
+  # shellcheck disable=SC2034
+  declare -g -A BASHCLI_TTY_STDERR_STYLES=()
+fi
+
+declare -g -A _BASHCLI_LIBRARIES_LOADED=()
 
 bashcli-debug() {
   case ${BASHCLI_DEBUG} in
@@ -23,6 +39,7 @@ bashcli-debug() {
   local fnName
   local minContextWidth=24
   local cliName=${BASHCLI_CLI_NAME}
+  local -n styles=BASHCLI_TTY_STDERR_STYLES
 
   if [[ -n "${FUNCNAME[1]}" && "${FUNCNAME[1]}" != source ]]; then
     fnName="${FUNCNAME[1]}"
@@ -43,22 +60,25 @@ bashcli-debug() {
     return 0
   fi
 
-  printf "[%s]%-${minContextWidth}s %s\n" "${_BASHCLI_COLORS[debug]}debug${_BASHCLI_COLORS[none]}" "(${context})" "${*//$'\n'/\\n}" >&2
+  printf "[%s]%-${minContextWidth}s %s\n" "${styles[debug]}debug${styles[none]}" "(${context})" "${*//$'\n'/\\n}" >&2
 }
 
 bashcli-info() {
   local IFS=' '
-  printf "[%s] %s\n" "${_BASHCLI_COLORS[info]}info${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
+  local -n styles=BASHCLI_TTY_STDERR_STYLES
+  printf "[%s] %s\n" "${styles[info]}info${styles[none]}" "${*//$'\n'/\\n}" >&2
 }
 
 bashcli-warn() {
   local IFS=' '
-  printf "[%s] %s\n" "${_BASHCLI_COLORS[warn]}warn${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
+  local -n styles=BASHCLI_TTY_STDERR_STYLES
+  printf "[%s] %s\n" "${styles[warn]}warn${styles[none]}" "${*//$'\n'/\\n}" >&2
 }
 
 bashcli-error() {
   local IFS=' '
-  printf "[%s] %s\n" "${_BASHCLI_COLORS[error]}error${_BASHCLI_COLORS[none]}" "${*//$'\n'/\\n}" >&2
+  local -n styles=BASHCLI_TTY_STDERR_STYLES
+  printf "[%s] %s\n" "${styles[error]}error${styles[none]}" "${*//$'\n'/\\n}" >&2
 }
 
 bashcli-fatal() {
