ensure compatibility with bash 5.1

diff --git a/src/bashcli b/src/bashcli
--- a/src/bashcli
+++ b/src/bashcli
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [[ ${BASH_VERSINFO[0]} -lt 5
-          || (${BASH_VERSINFO[0]} -eq 5 && ${BASH_VERSINFO[1]} -lt 2) ]]; then
-  echo "bash >= 5.2 required: ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" >&2
+          || (${BASH_VERSINFO[0]} -eq 5 && ${BASH_VERSINFO[1]} -lt 1) ]]; then
+  echo "bash >= 5.1 required: ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" >&2
   exit 1
 fi
 
